import pygame as pg

#MAP SETTING
MAP_WIDTH_TILE = 15
MAP_HEIGHT_TILE = 10
MAP_TILE_SIZE = 64

#WINDOWS SETTING
WINDOW_WIDTH= MAP_WIDTH_TILE*MAP_TILE_SIZE
WINDOW_HEIGHT=MAP_HEIGHT_TILE*MAP_TILE_SIZE
FPS = 60

#OTHER SETING
pg.font.init()
FONT = pg.font.Font("Fonts/Baloo2.ttf", 32)
button_color = (42,186,103)